# Autogenerated wrapper script for libmng_jll for i686-w64-mingw32
export limng

using JpegTurbo_jll
using LittleCMS_jll
using Zlib_jll
JLLWrappers.@generate_wrapper_header("libmng")
JLLWrappers.@declare_library_product(limng, "libmng.dll")
function __init__()
    JLLWrappers.@generate_init_header(JpegTurbo_jll, LittleCMS_jll, Zlib_jll)
    JLLWrappers.@init_library_product(
        limng,
        "bin\\libmng.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
